### ISSUE TITLE
searchNarratives method should use getServiceClient under the hood

### ISSUE THREAD

**Issue by charleshtrenholm** [kbase/ui-refresh-test#36]
searchNarratives.ts currently makes a `fetch` request to searchAPI2 instead of using `getServiceClient`, which summons the built in method from `@kbase/narrative-utils`. This is because narrative-utils is hardcoded to only use JSONRPC version 1.1 and SearchAPI2 requires JSONRPC version 2.0. Any other version specification will result in a 400 bad request. 

Once this behavior is fixed inside of `@kbase/narrative-utils`, we should update searchNarratives.ts to use the same static service client to ensure pattern consistency across the codebase.

**Comment by dakotablair** [comment]
We are using [RTK Query](https://github.com/kbase/ui-refresh-test/blob/main/docs/adrs/0004-RTK-Query.md) for asynchronous calls. Fortunately, [JSONRPC 2.0 has not caused major issues](https://github.com/kbase/ui-refresh-test/blob/main/src/common/api/utils/kbaseBaseQuery.ts#L42-L53) yet.
